# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GRASSGISColorTableImport
                                 A QGIS plugin
 Module for loading and applying GRASS color table files to raster data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-04-14
        copyright            : (C) 2024 by Josef Jehlička
        email                : jehlijos@cvut.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GRASSGISColorTableImport class from file GRASSGISColorTableImport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .GRASS_GIS_Color_Table_Import import GRASSGISColorTableImport
    return GRASSGISColorTableImport(iface)
