name: QGIS Color Table Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QGIS and Python
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ppa
        sudo apt-get update
        sudo apt-get install -y qgis python3.10 python3.10-dev python3-pip
        sudo apt-get install -y qgis-plugin-grass
        python3.10 -m pip install --upgrade pip
        python3.10 -m pip install pytest pytest-qt PyQt6
        sudo apt-get install -y gdb

    - name: Set up QGIS environment variables
      run: |
        echo "QGIS_PREFIX_PATH=/usr" >> $GITHUB_ENV
        echo "PYTHONPATH=/usr/share/qgis/python:$GITHUB_WORKSPACE" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/usr/lib" >> $GITHUB_ENV
        echo "QGIS_DEBUG=0" >> $GITHUB_ENV
        echo "QGIS_LOG_FILE=/dev/null" >> $GITHUB_ENV

    - name: Verify QGIS and Python Installation
      run: |
        qgis --version
        python3.10 --version

    - name: Debug QGIS Initialization with GDB
      run: |
        gdb -ex "run" -ex "bt" --args python3.10 -c "from qgis.core import QgsApplication; QgsApplication.setPrefixPath('/usr', True); QgsApplication.initQgis()"

    - name: List directory contents
      run: |
        echo "Contents of the repository root:"
        ls -R $GITHUB_WORKSPACE
        echo "Contents of the test directory:"
        ls -R $GITHUB_WORKSPACE/test

    - name: Run tests
      env:
        QGIS_PREFIX_PATH: /usr
        PYTHONPATH: /usr/share/qgis/python:$GITHUB_WORKSPACE
        LD_LIBRARY_PATH: /usr/lib
        QGIS_DEBUG: 0
        QGIS_LOG_FILE: /dev/null
      run: pytest test/test_qgis_color_func.py
