name: QGIS Color Table Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      QGIS_PREFIX_PATH: "/usr/share/qgis"
      PYTHONPATH: "${PYTHONPATH}:${QGIS_PREFIX_PATH}/python"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List directory contents
      run: ls -R

    - name: Set up QGIS
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install -y qgis python3-qgis

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-qt PyQt5

    - name: Initialize QGIS environment
      run: |
        export PYTHONPATH="${PYTHONPATH}:${QGIS_PREFIX_PATH}/python"
        export QGIS_PREFIX_PATH="/usr"
        export LD_LIBRARY_PATH="${QGIS_PREFIX_PATH}/lib"
        export QGIS_DEBUG=0
        export QGIS_LOG_FILE=/dev/null
        # Install qgis.testing module
        pip install qgis

    - name: Run tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:${QGIS_PREFIX_PATH}/python"
        pytest test/test_qgis_color_func.py
