name: QGIS Color Table Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      QGIS_VERSION: '3.28'  
      PYTHON_VERSION: '3'   
      QGIS_PREFIX_PATH: '/usr'
      PYTHONPATH: '${QGIS_PREFIX_PATH}/share/qgis/python'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QGIS and Python
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ppa
        sudo apt-get update
        sudo apt-get install -y qgis python3-qgis qgis-plugin-grass
        sudo apt-get install -y python3 python3-dev python3-pip
        python3 -m pip install --upgrade pip
        pip3 install pytest pytest-qt PyQt5

    - name: Set up QGIS environment variables
      run: |
        export QGIS_PREFIX_PATH="/usr"
        export PYTHONPATH="${QGIS_PREFIX_PATH}/share/qgis/python"
        export LD_LIBRARY_PATH="${QGIS_PREFIX_PATH}/lib"
        export QGIS_DEBUG=0
        export QGIS_LOG_FILE=/dev/null
        echo "QGIS_PREFIX_PATH=${QGIS_PREFIX_PATH}"
        echo "PYTHONPATH=${PYTHONPATH}"
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
    
    - name: Verify QGIS and Python Installation
      run: |
        qgis --version
        python3 --version

    - name: Debug QGIS Initialization
      run: |
        python3 -X faulthandler -c "from qgis.core import QgsApplication; QgsApplication.setPrefixPath('${QGIS_PREFIX_PATH}', True); QgsApplication.initQgis()"

    - name: Run tests
      run: pytest test/test_qgis_color_func.py
