name: QGIS Color Table Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      QGIS_VERSION: '3.34'
      PYTHON_VERSION: '3.10'
      QGIS_PREFIX_PATH: '/usr'
      PYTHONPATH: '${QGIS_PREFIX_PATH}/share/qgis/python'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QGIS and Python
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ppa
        sudo apt-get update
        sudo apt-get install -y qgis python3.10 python3.10-dev python3-pip
        sudo apt-get install -y qgis-plugin-grass
        python3.10 -m pip install --upgrade pip
        python3.10 -m pip install pytest pytest-qt PyQt6
        sudo apt-get install -y gdb
        
    - name: Set up QGIS environment variables
      run: |
        export QGIS_PREFIX_PATH="/usr"
        export PYTHONPATH="${QGIS_PREFIX_PATH}/share/qgis/python"
        export LD_LIBRARY_PATH="${QGIS_PREFIX_PATH}/lib"
        export QGIS_DEBUG=0
        export QGIS_LOG_FILE=/dev/null
        echo "QGIS_PREFIX_PATH=${QGIS_PREFIX_PATH}"
        echo "PYTHONPATH=${PYTHONPATH}"
        echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"

    - name: Verify QGIS and Python Installation
      run: |
        qgis --version
        python3.10 --version

    - name: Debug QGIS Initialization with GDB
      run: |
        gdb -ex "run" -ex "bt" --args python3.8 -c "from qgis.core import QgsApplication; QgsApplication.setPrefixPath('${QGIS_PREFIX_PATH}', True); QgsApplication.initQgis()"

    - name: Run tests
      run: pytest test/test_qgis_color_func.py
