name: QGIS Color Table Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      QGIS_VERSION: '3.34'  
      PYTHON_VERSION: '3.10'   
      QGIS_PREFIX_PATH: '/usr'
      PYTHONPATH: '${QGIS_PREFIX_PATH}/share/qgis/python'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up QGIS and Python
      run: |
        sudo add-apt-repository -y ppa:ubuntugis/ppa
        sudo apt-get update
        sudo apt-get install -y qgis python3-qgis qgis-plugin-grass

        python${PYTHON_VERSION} -m pip install --upgrade pip
        pip${PYTHON_VERSION} install pytest pytest-qt PyQt5

    - name: Set up QGIS environment variables
      run: |
        export PYTHONPATH="${PYTHONPATH}:${QGIS_PREFIX_PATH}/share/qgis/python"
        export QGIS_PREFIX_PATH="/usr"
        export LD_LIBRARY_PATH="${QGIS_PREFIX_PATH}/lib"
        export QGIS_DEBUG=0
        export QGIS_LOG_FILE=/dev/null

    - name: Initialize QGIS
      run: python${PYTHON_VERSION} -c "from qgis.core import QgsApplication; QgsApplication.setPrefixPath('${QGIS_PREFIX_PATH}', True); QgsApplication.initQgis()"

    - name: Run tests
      run: pytest test/test_qgis_color_func.py
